import scons_tools

bp_extensions_env = scons_tools.MakeEnvironment()
bp_extensions_env.SetupPackages(["boost.python"])
bp_extensions_env.Append(CPPPATH = "#")

if ARGUMENTS.get("debug", 0):
    build_dir = "build.debug"
else:
    build_dir = "build"
Export("build_dir")

Export("bp_extensions_env")
lib = SConscript("libs/python/src/SConscript", variant_dir="%s/python/src" % build_dir, duplicate=False)
libpath = os.path.abspath("%s/python/src" % build_dir)
if os.environ.has_key("LD_LIBRARY_PATH"):
    bp_extensions_env["ENV"]["LD_LIBRARY_PATH"] = "%s:%s" % (libpath, os.environ["LD_LIBRARY_PATH"])
else:
    bp_extensions_env["ENV"]["LD_LIBRARY_PATH"] = libpath
bp_extensions_env.Append(LIBPATH=libpath)

SConscript("libs/python/test/SConscript", variant_dir="%s/python/test" % build_dir)
