import scons_tools

bp_extensions_env = scons_tools.MakeEnvironment()
bp_extensions_env.SetupPackages(["boost.python"])
bp_extensions_env.Append(CPPPATH = "#")

Export("bp_extensions_env")
SConscript("libs/python/test/SConscript")
