//////////////////////////////////////////////////////////////////////////////
//
//  assert_check.cpp
//
//////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) David B. Held 2002-2003.
//
//  See http://www.boost.org/ for most recent version, including documentation.
//
//  Permission is hereby granted, free of charge, to any person or organization
//  obtaining a copy of the software and accompanying documentation covered by
//  this license (the "Software") to use, reproduce, display, distribute,
//  execute, and transmit the Software, and to prepare derivative works of the
//  Software, and to permit third-parties to whom the Software is furnished to
//  do so, all subject to the following:
//
//  The copyright notices in the Software and this entire statement, including
//  the above license grant, this restriction and the following disclaimer,
//  must be included in all copies of the Software, in whole or in part, and
//  all derivative works of the Software, unless such copies or derivative
//  works are solely in the form of machine-executable object code generated by
//  a source language processor.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////////
//
//  This is a checking policy testing program for the policy-based smart
//  pointer library.  Every test should fail with an assert or an exception
//  See libs/policy_ptr/doc/index.html
//
//////////////////////////////////////////////////////////////////////////////
#define BOOST_SMART_POINTER_BASIC_INTERFACE

#include <string>
#include <iostream>
#include <boost/test/unit_test.hpp>
#include "../smart_ptr.hpp"

class object
{
public:
    object(int x) : x_(x) { }
    int x(void) const { return x_; }
private:
    int x_;
};

// Hack for VC's lack of ADL
namespace boost
{
    namespace test = unit_test_framework;
    using mpl::_;

    void assert_check_test(void)
    {
        smart_ptr<object, assert_check<_> > p;
        p->x();
    }

    void assert_check_strict_test1(void)
    {
        smart_ptr<object, assert_check_strict<_> > p;
    }

    void assert_check_strict_test2(void)
    {
        object* x = 0;
        smart_ptr<object, assert_check_strict<_> > p(x);
    }

    void assert_check_strict_test3(void)
    {
        object* x = new object(29);
        smart_ptr<object, assert_check_strict<_> > p(x);
        release(p, x);
        delete x;
        p->x();
    }

    void reject_null_static_test1(void)
    {
        object* x = new object(38);
        smart_ptr<object, reject_null_static<_> > p(x);
        reset(p, 0);
    }

    void reject_null_static_test2(void)
    {
        object* x = new object(47);
        smart_ptr<object, reject_null_static<_> > p(x);
        release(p, x);
        delete x;
        p->x();
    }

    void reject_null_test(void)
    {
        smart_ptr<object, reject_null<_> > p;
        p->x();
    }

    void reject_null_strict_test1(void)
    {
        object* x = 0;
        smart_ptr<object, reject_null_strict<_> > p(x);
    }

    void reject_null_strict_test2(void)
    {
        object* x = new object(56);
        smart_ptr<object, reject_null_strict<_> > p(x);
        release(p, x);
        delete x;
        p->x();
    }
}

using namespace boost;
test::test_suite* init_unit_test_suite(int argc, char* argv[])
{
    test::test_suite* test = BOOST_TEST_SUITE("smart_ptr assert_check test");

    test->add(BOOST_TEST_CASE(&assert_check_test));
    test->add(BOOST_TEST_CASE(&assert_check_strict_test1));
    test->add(BOOST_TEST_CASE(&assert_check_strict_test2));
    test->add(BOOST_TEST_CASE(&assert_check_strict_test3));
    test->add(BOOST_TEST_CASE(&reject_null_static_test1));
    test->add(BOOST_TEST_CASE(&reject_null_static_test2));
    test->add(BOOST_TEST_CASE(&reject_null_test));
    test->add(BOOST_TEST_CASE(&reject_null_strict_test1));
    test->add(BOOST_TEST_CASE(&reject_null_strict_test2));

    return test;
}
