#ifndef BOOST_RPC_CONFIG_HPP
#define BOOST_RPC_CONFIG_HPP

#define BOOST_RPC_MAX_ARGS 4
#define BOOST_RPC_HEADER_BUFFER_SIZE 200
#define BOOST_RPC_RPC_BUFFER_SIZE 1000

#endif // BOOST_RPC_CONFIG_HPP
