#undef BOOST_ARITY_NUM_ARGS
#undef BOOST_ARITY_NUM_ARGS_INC

#undef BOOST_ARITY_INSERT

#undef BOOST_ARITY_ARG_TYPE_NAME
#undef BOOST_ARITY_ARG_STORABLE_NAME

#undef BOOST_ARITY_TYPE
#undef BOOST_ARITY_TYPES

#undef BOOST_ARITY_STORABLE_TYPE
#undef BOOST_ARITY_STORABLE_TYPES

#undef BOOST_ARITY_STORABLE
#undef BOOST_ARITY_STORABLES

#undef BOOST_ARITY_ON_STORABLE
#undef BOOST_ARITY_ON_STORABLES

#undef BOOST_ARITY_TYPE_PARM
#undef BOOST_ARITY_TYPE_PARMS

#undef BOOST_ARITY_ON_PARM
#undef BOOST_ARITY_ON_PARMS

#undef BOOST_ARITY_COMMA