// Boost.Pinhole library

// Copyright Jared McIntyre 2007. Use, modification and
// distribution is subject to the Boost Software License, Version
// 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

// For more information, see http://www.boost.org

#define BOOST_TEST_MODULE PinholeLib
#include <boost/test/unit_test.hpp>
#include "TestClassesAndConstants.h"

// I can hide these two line if I don't do everything in headers
boost::shared_ptr<property_manager> property_manager::m_instance(new property_manager);
event_source* event_source::m_instance = 0;

BOOST_AUTO_TEST_CASE( TestSetGetFloat )
{
    TestPropertyGroup testGroup;
    
	float fValue;
	testGroup.set_as_string( PROPERTY_FLOAT_1, PROPERTY_FLOAT_1_STRING_VALUE );
	BOOST_CHECK( from_string<float>(fValue, testGroup.get_as_string(PROPERTY_FLOAT_1), std::dec) );
	BOOST_CHECK_EQUAL( PROPERTY_FLOAT_1_VALUE, fValue );
}

BOOST_AUTO_TEST_CASE( TestSetGetFloatVar )
{
    TestPropertyGroup testGroup;
    
	float fValue;
	testGroup.set_as_string( PROPERTY_FLOAT_1_VAR, PROPERTY_FLOAT_1_STRING_VALUE );
	BOOST_CHECK( from_string<float>(fValue, testGroup.get_as_string(PROPERTY_FLOAT_1_VAR), std::dec) );
	BOOST_CHECK_EQUAL( PROPERTY_FLOAT_1_VALUE, fValue );
}

BOOST_AUTO_TEST_CASE( TestFloatPropertyType )
{
    TestPropertyGroup_4 testGroup;
    
    BOOST_CHECK( typeid(bool) != testGroup.get_type_info(PROPERTY_FLOAT_1) );
    BOOST_CHECK( typeid(int) != testGroup.get_type_info(PROPERTY_FLOAT_1) );
    BOOST_CHECK( typeid(float) == testGroup.get_type_info(PROPERTY_FLOAT_1) );
    BOOST_CHECK( typeid(double) != testGroup.get_type_info(PROPERTY_FLOAT_1) );
    BOOST_CHECK( typeid(std::string) != testGroup.get_type_info(PROPERTY_FLOAT_1) );

	const FloatEditor *pEditor = dynamic_cast<const FloatEditor*>(testGroup.get_metadata( PROPERTY_FLOAT_1 ));
	BOOST_CHECK( pEditor != NULL );
	BOOST_CHECK( testGroup.get_metadata(PROPERTY_FLOAT_1)->getEditorPropertyType() == FloatType );
}

BOOST_AUTO_TEST_CASE( TestFloatGetControlType )
{
    TestPropertyGroup_4 testGroup;
    
	const FloatEditor *pEditor = dynamic_cast<const FloatEditor*>(testGroup.get_metadata( PROPERTY_FLOAT_1 ));
	BOOST_CHECK( pEditor->GetControlType() == EditBox );
}

BOOST_AUTO_TEST_CASE( TestFloatGetUIOverrideType )
{
    TestPropertyGroup_4 testGroup;
    
	const FloatEditor *pEditor = dynamic_cast<const FloatEditor*>(testGroup.get_metadata( PROPERTY_FLOAT_2 ));
	BOOST_CHECK( pEditor->GetControlType() == Tracker );
}

BOOST_AUTO_TEST_CASE( TestFloatHighLowIncrement )
{
    TestPropertyGroup_4 testGroup;
    
	const FloatEditor *pEditor = dynamic_cast<const FloatEditor*>(testGroup.get_metadata( PROPERTY_FLOAT_2 ));
	BOOST_CHECK_EQUAL( FLOAT_LOW, pEditor->getLowRange() );
	BOOST_CHECK_EQUAL( FLOAT_HIGH, pEditor->getHighRange() );
	BOOST_CHECK_EQUAL( FLOAT_INCREMENT, pEditor->getIncrement() );
}

BOOST_AUTO_TEST_CASE( TestFloatGetRange )
{
    TestPropertyGroup_4 testGroup;
    
	const FloatEditor *pEditor = dynamic_cast<const FloatEditor*>(testGroup.get_metadata( PROPERTY_FLOAT_2 ));
	BOOST_CHECK( pEditor->UseRange() == true );
}

BOOST_AUTO_TEST_CASE( TestAutoGeneratedDesignerFloat )
{
    TestAutoGeneratedDesigners testGroup;
    
	const Editor* pEditor = testGroup.get_metadata(PROPERTY_FLOAT_1);
	BOOST_CHECK( NULL != dynamic_cast<const FloatEditor*>(pEditor) );
}

BOOST_AUTO_TEST_CASE( TestUpDownEditor)
{
    TestUpDownGroup testGroup;
    
	const Editor* pEditor = testGroup.get_metadata(PROPERTY_FLOAT_1);
	BOOST_CHECK( pEditor->GetControlType() == UpDown );
}