Quickbook Doxygen Index Prototype Wed Mar 31 15:44:54 2010 xInt eXtended Integer Library
-
xint::detail Namespace Reference
Classes
struct token
struct base_random_generator
struct random_generator
struct data_t
Typedefs
typedef boost::uintmax_t doubledigit_t
typedef boost::uint_t
< std::numeric_limits
< doubledigit_t >::digits/2 >
::fast digit_t
typedef boost::function
< unsigned int()> random_t
Functions
void set_random_generator (random_t fn, base_random_generator *obj)
unsigned int get_random ()
Variables
const size_t bits_per_digit = std::numeric_limits<digit_t>::digits
const digit_t digit_hibit = (digit_t(1) << (bits_per_digit-1))
const doubledigit_t doubledigit_hibit = (doubledigit_t(1) << (bits_per_digit*2-1))
const doubledigit_t digit_overflowbit = (doubledigit_t(1) << bits_per_digit)
const digit_t digit_mask = digit_t(digit_overflowbit-1)
const std::string nan_text
Typedef Documentation
typedef boost::uint_t<std::numeric_limits<doubledigit_t>::digits / 2>::fast xint::detail::digit_t
Definition at line 40 of file xint.hpp.
typedef boost::uintmax_t xint::detail::doubledigit_t
Definition at line 38 of file xint.hpp.
typedef boost::function<unsigned int ()> xint::detail::random_t
Definition at line 68 of file xint.hpp.
Function Documentation
unsigned int xint::detail::get_random ()
void xint::detail::set_random_generator (random_t fn, base_random_generator * obj)
Referenced by xint::set_random_generator().
Variable Documentation
const size_t xint::detail::bits_per_digit = std::numeric_limits<digit_t>::digits
Definition at line 42 of file xint.hpp.
Referenced by xint::integer::_init(), xint::detail::data_t::shift_left(), and xint::detail::data_t::shift_right().
const digit_t xint::detail::digit_hibit = (digit_t(1) << (bits_per_digit-1))
Definition at line 43 of file xint.hpp.
const digit_t xint::detail::digit_mask = digit_t(digit_overflowbit-1)
Definition at line 46 of file xint.hpp.
Referenced by xint::integer::_init(), and xint::integer::integer().
const doubledigit_t xint::detail::digit_overflowbit = (doubledigit_t(1) << bits_per_digit)
Definition at line 45 of file xint.hpp.
Referenced by xint::detail::data_t::add(), xint::detail::data_t::invert(), xint::detail::data_t::subtract(), and xint::to().
const doubledigit_t xint::detail::doubledigit_hibit = (doubledigit_t(1) << (bits_per_digit*2-1))
Definition at line 44 of file xint.hpp.
const std::string xint::detail::nan_text
Referenced by xint::operator<<(), and xint::operator>>().
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright © 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Wed Mar 31 15:44:54 2010