#include <geometry/geometry.hpp>
#include <boost/assign/std.hpp>
#include <boost/foreach.hpp>
#include <boost/bind.hpp>
#include <boost/bind/placeholders.hpp>
#include <boost/signal.hpp>
#include <boost/gil/utilities.hpp>
#include <boost/gil/typedefs.hpp>
#include <utility>
