###############################################################################
# Project makefile: dt
###############################################################################

IS_DEBUG = true
#
#  Specify project root
#

P_ROOT := ./

#
#  Specify include dirs
#

P_INC := $(P_ROOT)

#
# Project files
#

SRC := \


#
# Include rules etc. 
#
include $(MAKE_ROOT)Makefile.common


###############################################################################
# local programs
###############################################################################

# note: the library must be specified AFTER object files
