Quickbook Doxygen Index Prototype Tue Mar 30 18:10:43 2010 xInt eXtended Integer Library
-
xint::integer Class Reference
#include <xint.hpp>
Public Member Functions
integer ()
The extended integer class.
integer (const integer &b)
(Can throw std::overflow_error if not enough memory to construct a new integer).
template<typename T >
integer (const T &n)
integer (const std::string &str, size_t base=10)
Copy constructs a integer from a digits string (decimal by default).
integer (const not_a_number &)
Constructs an extended integer with the NotANumber value;.
~integer ()
bool odd () const
bool even () const
int sign () const
bool nan () const
size_t hex_digits () const
integer & operator= (const integer &c)
integer & operator+= (const integer &b)
integer & operator-= (const integer &b)
integer & operator*= (const integer &b)
integer & operator/= (const integer &b)
integer & operator%= (const integer &b)
integer & operator++ ()
integer & operator-- ()
integer operator++ (int)
integer operator-- (int)
integer & operator&= (const integer &n)
integer & operator|= (const integer &n)
integer & operator^= (const integer &n)
integer operator<< (size_t shift) const
integer operator>> (size_t shift) const
integer & operator<<= (size_t shift)
integer & operator>>= (size_t shift)
detail::data_t * _get_data ()
const detail::data_t * _get_data () const
detail::digit_t _get_digit (size_t index) const
size_t _get_length () const
void _set_negative (bool negative)
void _make_unique ()
void _throw_if_nan () const
Static Public Member Functions
static const integer & zero ()
Extended integer holding zero.
static const integer & one ()
Extended integer holding one.
Private Member Functions
void _init (detail::digit_t init=0)
void _init (const integer &c)
void _init (boost::uintmax_t n)
void _attach ()
void _detach ()
Private Attributes
detail::data_t * data
Raw data representing an extended integer.
Static Private Attributes
static const integer * cZero = 0
static const integer * cOne = 0
Detailed Description
Definition at line 93 of file xint.hpp.
Constructor & Destructor Documentation
xint::integer::integer ()
The extended integer class.
Constructs a default integer, value zero. (Can throw std::overflow_error if not enough memory to construct a new integer).
Definition at line 22 of file integer.cpp.
References _init().
Referenced by one(), and zero().
xint::integer::integer (const integer & b)
(Can throw std::overflow_error if not enough memory to construct a new integer).
Copy constructs a integer from another integer.
Definition at line 26 of file integer.cpp.
References _init(), data, and nan().
template<typename T > xint::integer::integer (const T & n) [inline]
Definition at line 319 of file xint.hpp.
References _init(), _set_negative(), and xint::detail::digit_mask.
xint::integer::integer (const std::string & str, size_t base = 10) [explicit]
Copy constructs a integer from a digits string (decimal by default).
Definition at line 31 of file integer.cpp.
References _init(), and xint::from_string().
xint::integer::integer (const not_a_number &) [explicit]
Constructs an extended integer with the NotANumber value;.
Definition at line 35 of file integer.cpp.
References data.
xint::integer::~integer ()
Definition at line 39 of file integer.cpp.
References _detach().
Member Function Documentation
void xint::integer::_attach () [private]
Definition at line 80 of file integer.cpp.
References xint::detail::data_t::attach(), and data.
Referenced by _init(), _make_unique(), and operator=().
void xint::integer::_detach () [private]
Definition at line 84 of file integer.cpp.
References data, and xint::detail::data_t::detach().
Referenced by _make_unique(), operator=(), and ~integer().
const detail::data_t* xint::integer::_get_data () const [inline]
Definition at line 142 of file xint.hpp.
References data.
detail::data_t* xint::integer::_get_data () [inline]
Returns:
raw data representing an extended integer.
Definition at line 138 of file xint.hpp.
References data.
detail::digit_t xint::integer::_get_digit (size_t index) const
Definition at line 210 of file integer.cpp.
References data, and xint::detail::data_t::digits.
Referenced by even(), odd(), sign(), and xint::to().
size_t xint::integer::_get_length () const
Definition at line 214 of file integer.cpp.
References data, and xint::detail::data_t::mLength.
Referenced by sign(), and xint::to().
void xint::integer::_init (boost::uintmax_t n) [private]
Definition at line 61 of file integer.cpp.
References _attach(), xint::detail::data_t::alloc(), xint::detail::bits_per_digit, data, xint::detail::digit_mask, xint::detail::data_t::digits, and xint::detail::data_t::skipLeadingZeros().
void xint::integer::_init (const integer & c) [private]
Definition at line 52 of file integer.cpp.
References _attach(), and data.
void xint::integer::_init (detail::digit_t init = 0) [private]
Definition at line 43 of file integer.cpp.
References _attach(), and data.
Referenced by integer().
void xint::integer::_make_unique ()
Definition at line 88 of file integer.cpp.
References _attach(), _detach(), data, and xint::detail::data_t::mCopies.
Referenced by operator+=(), operator-=(), operator<<=(), and operator>>=().
void xint::integer::_set_negative (bool negative)
Definition at line 101 of file integer.cpp.
References xint::negate(), and sign().
Referenced by integer().
void xint::integer::_throw_if_nan () const
Definition at line 218 of file integer.cpp.
References nan().
Referenced by even(), hex_digits(), odd(), sign(), and xint::to().
bool xint::integer::even () const
Returns:
true if extended integer is even.
Definition at line 110 of file integer.cpp.
References _get_digit(), and _throw_if_nan().
size_t xint::integer::hex_digits () const
Returns:
the number of hex digits to show the integer.
Definition at line 126 of file integer.cpp.
References _throw_if_nan(), and xint::log2().
bool xint::integer::nan () const
Returns:
true if extended integer is Not-a-Number.
Definition at line 122 of file integer.cpp.
References data.
Referenced by _throw_if_nan(), integer(), and xint::operator<<().
bool xint::integer::odd () const
Returns:
true if extended integer is odd.
Definition at line 105 of file integer.cpp.
References _get_digit(), and _throw_if_nan().
const integer & xint::integer::one () [static]
Extended integer holding one.
Definition at line 205 of file integer.cpp.
References cOne, and integer().
Referenced by operator++(), and operator--().
integer & xint::integer::operator%= (const integer & b)
Definition at line 171 of file integer.cpp.
References xint::mod().
integer & xint::integer::operator&= (const integer & n)
Definition at line 180 of file integer.cpp.
References xint::bitwise_and().
integer & xint::integer::operator*= (const integer & b)
Definition at line 169 of file integer.cpp.
References xint::multiply().
integer xint::integer::operator++ (int)
Definition at line 175 of file integer.cpp.
References one().
integer & xint::integer::operator++ ()
Definition at line 173 of file integer.cpp.
References one().
integer & xint::integer::operator+= (const integer & b)
Definition at line 132 of file integer.cpp.
References _make_unique(), xint::add(), xint::detail::data_t::add(), data, xint::detail::data_t::mLength, and sign().
integer xint::integer::operator-- (int)
Definition at line 176 of file integer.cpp.
References one().
integer & xint::integer::operator-- ()
Definition at line 174 of file integer.cpp.
References one().
integer & xint::integer::operator-= (const integer & b)
Definition at line 146 of file integer.cpp.
References _make_unique(), data, sign(), xint::subtract(), and xint::detail::data_t::subtract().
integer & xint::integer::operator/= (const integer & b)
Definition at line 170 of file integer.cpp.
References xint::divide().
integer xint::integer::operator<< (size_t shift) const
Definition at line 178 of file integer.cpp.
References xint::shift_left().
integer & xint::integer::operator<<= (size_t shift)
Definition at line 184 of file integer.cpp.
References _make_unique(), data, and xint::detail::data_t::shift_left().
integer & xint::integer::operator= (const integer & c)
Definition at line 158 of file integer.cpp.
References _attach(), _detach(), and data.
integer xint::integer::operator>> (size_t shift) const
Definition at line 179 of file integer.cpp.
References xint::shift_right().
integer & xint::integer::operator>>= (size_t shift)
Definition at line 192 of file integer.cpp.
References _make_unique(), data, and xint::detail::data_t::shift_right().
integer & xint::integer::operator^= (const integer & n)
Definition at line 182 of file integer.cpp.
References xint::bitwise_xor().
integer & xint::integer::operator|= (const integer & n)
Definition at line 181 of file integer.cpp.
References xint::bitwise_or().
int xint::integer::sign () const
Returns:
-1 if extended integer is < 0.
Definition at line 115 of file integer.cpp.
References _get_digit(), _get_length(), _throw_if_nan(), data, and xint::detail::data_t::mIsNegative.
Referenced by _set_negative(), operator!(), operator+=(), operator-=(), xint::operator<<(), and xint::to().
const integer & xint::integer::zero () [static]
Extended integer holding zero.
Definition at line 200 of file integer.cpp.
References cZero, and integer().
Member Data Documentation
const integer * xint::integer::cOne = 0 [static, private]
Definition at line 157 of file xint.hpp.
Referenced by one().
const integer * xint::integer::cZero = 0 [static, private]
Definition at line 156 of file xint.hpp.
Referenced by zero().
detail::data_t* xint::integer::data [private]
Raw data representing an extended integer.
Definition at line 158 of file xint.hpp.
Referenced by _attach(), _detach(), _get_data(), _get_digit(), _get_length(), _init(), _make_unique(), integer(), nan(), operator+=(), operator-=(), operator<<=(), operator=(), operator>>=(), and sign().
The documentation for this class was generated from the following files:
I:/boost-sandbox/xInt/boost/xint/xint.hpp
I:/boost-sandbox/xInt/boost/xint/src/integer.cpp
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Tue Mar 30 18:10:43 2010