Quickbook Doxygen Index Prototype Tue Mar 30 18:10:43 2010 xInt eXtended Integer Library
-
I:/boost-sandbox/xInt/boost/xint/src/compare.cpp File Reference
#include "../xint.hpp"
#include "../xint_data_t.hpp"
Namespaces
namespace xint
namespace for all extended integer classes and functions.
Functions
int xint::compare (const integer &b1, const integer &b2, bool ignoresign)
bool operator! (const xint::integer &num1)
bool operator== (const xint::integer &num1, const xint::integer &num2)
bool operator!= (const xint::integer &num1, const xint::integer &num2)
bool operator< (const xint::integer &num1, const xint::integer &num2)
bool operator> (const xint::integer &num1, const xint::integer &num2)
bool operator<= (const xint::integer &num1, const xint::integer &num2)
bool operator>= (const xint::integer &num1, const xint::integer &num2)
Function Documentation
bool operator! (const xint::integer & num1)
Definition at line 54 of file compare.cpp.
References xint::integer::sign().
bool operator!= (const xint::integer & num1, const xint::integer & num2)
Definition at line 56 of file compare.cpp.
References xint::compare().
bool operator< (const xint::integer & num1, const xint::integer & num2)
Definition at line 57 of file compare.cpp.
References xint::compare().
bool operator<= (const xint::integer & num1, const xint::integer & num2)
Definition at line 59 of file compare.cpp.
References xint::compare().
bool operator== (const xint::integer & num1, const xint::integer & num2)
Definition at line 55 of file compare.cpp.
References xint::compare().
bool operator> (const xint::integer & num1, const xint::integer & num2)
Definition at line 58 of file compare.cpp.
References xint::compare().
bool operator>= (const xint::integer & num1, const xint::integer & num2)
Definition at line 60 of file compare.cpp.
References xint::compare().
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright © 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Tue Mar 30 18:10:43 2010