Quickbook Doxygen Index Prototype Wed Mar 31 15:44:54 2010 xInt eXtended Integer Library
-
xint Namespace Reference
Namespaces
namespace detail
Classes
class integer
class strong_random_generator
class invalid_base
class invalid_digit
class invalid_modulus
class divide_by_zero
class cannot_represent
class too_big
class not_a_number
class no_strong_random
class overflow_error
Typedefs
typedef std::auto_ptr
< detail::token > token
typedef boost::function< bool()> callback_t
Functions
bool getbit (const integer &n, size_t bit)
void setbit (integer &n, size_t bit)
void clearbit (integer &n, size_t bit)
size_t lowestbit (const integer &n, size_t defaultValue)
size_t highestbit (const integer &n, size_t defaultValue)
integer bitwise_and (const integer &n1, const integer &n2)
integer bitwise_or (const integer &n1, const integer &n2)
integer bitwise_xor (const integer &n1, const integer &n2)
integer shift (const integer &n, int byBits)
integer shift_left (const integer &_n, size_t byBits)
integer shift_right (const integer &_n, size_t byBits)
int compare (const integer &b1, const integer &b2, bool ignoresign)
bool operator! (const xint::integer &num1)
bool operator== (const xint::integer &num1, const xint::integer &num2)
bool operator!= (const xint::integer &num1, const xint::integer &num2)
bool operator< (const xint::integer &num1, const xint::integer &num2)
bool operator> (const xint::integer &num1, const xint::integer &num2)
bool operator<= (const xint::integer &num1, const xint::integer &num2)
bool operator>= (const xint::integer &num1, const xint::integer &num2)
std::string to_string (const integer &n, size_t base, bool upperCase)
integer from_string (const std::string &str, size_t base)
integer from_binary (const std::string &str)
std::string to_binary (const integer &n)
bool exceptions_allowed ()
token block_exceptions ()
token allow_exceptions ()
integer gcd (const integer &num1, const integer &num2)
integer lcm (const integer &num1, const integer &num2)
integer invmod (const integer &n, const integer &m)
bool opt_secure_mode ()
bool opt_thread_safe ()
size_t log2 (const integer &n)
integer mod (const integer &n, const integer &modBy)
integer mulmod (const integer &n, const integer &by, const integer &modulus)
integer sqrmod (const integer &n, const integer &modulus)
integer powmod (const integer &n, const integer &exponent, const integer &modulus, bool noMontgomery)
digit_t inverse0 (const integer &n)
integer montgomeryR (const integer &n)
integer toMontgomeryForm (const integer &n, const integer &m)
integer fromMontgomeryForm (const integer &n, const integer &m)
integer montgomeryMultiplyMod (const integer &a, const integer &b, const integer &n, digit_t nPrime0)
integer montgomeryPowerMod (const integer &a, const integer &e, const integer &n)
const integer & operator+ (const integer &a)
integer operator- (const integer &a)
integer operator+ (const integer &num1, const integer &num2)
integer operator- (const integer &num1, const integer &num2)
integer operator* (const integer &num1, const integer &num2)
integer operator/ (const integer &num1, const integer &num2)
integer operator% (const integer &num1, const integer &num2)
integer operator& (const integer &n1, const integer &n2)
integer operator| (const integer &n1, const integer &n2)
integer operator^ (const integer &n1, const integer &n2)
integer pow2 (size_t exponent)
integer sqr (const integer &n)
integer pow (const integer &n, const integer &exponent)
integer factorial (size_t n)
int is_prime (const integer &n, callback_t callback)
integer random_prime (size_t sizeInBits, callback_t callback)
integer abs (const integer &n)
integer negate (const integer &_n)
integer add (const integer &n1, const integer &n2)
integer subtract (const integer &n1, const integer &n2)
integer multiply (const integer &n, const integer &by)
integer divide (const integer &dividend, const integer &divisor)
std::pair< integer, integer > divide_r (const integer &d1, const integer &d2)
strong_random_generator::result_type
strong_random_generator::min BOOST_PREVENT_MACRO_SUBSTITUTION () const
integer random_by_size (size_t bits, bool highBitOn, bool lowBitOn, bool canBeNegative)
integer sqrt (const integer &n)
template<typename T >
T to (const integer &n)
template<typename T >
void set_random_generator (T &gen)
template<typename charT , typename traits >
std::basic_ostream< charT,
traits > & operator<< (std::basic_ostream< charT, traits > &out, const xint::integer &n)
template<typename charT , typename traits >
std::basic_istream< charT,
traits > & operator>> (std::basic_istream< charT, traits > &in, xint::integer &n)
bool testAll ()
bool testBitManipulations ()
bool testAddSubtract ()
bool testMultiply ()
bool testDivideMod ()
bool testConvert ()
bool testStreams ()
bool testMontyMultiply ()
bool testMontyPowerMod ()
Variables
const callback_t no_callback
const size_t autobase = (std::numeric_limits<size_t>::max)()
Typedef Documentation
typedef boost::function<bool ()> xint::callback_t
Definition at line 76 of file xint.hpp.
typedef std::auto_ptr<detail::token> xint::token
Definition at line 74 of file xint.hpp.
Function Documentation
integer xint::abs (const integer & n)
Referenced by operator<<().
integer xint::add (const integer & n1, const integer & n2)
Referenced by xint::integer::operator+=().
token xint::allow_exceptions ()
Referenced by operator>>().
integer xint::bitwise_and (const integer & n1, const integer & n2)
Referenced by xint::integer::operator&=().
integer xint::bitwise_or (const integer & n1, const integer & n2)
Referenced by xint::integer::operator|=().
integer xint::bitwise_xor (const integer & n1, const integer & n2)
Referenced by xint::integer::operator^=().
token xint::block_exceptions ()
strong_random_generator::result_type strong_random_generator::max xint::BOOST_PREVENT_MACRO_SUBSTITUTION () const
Definition at line 176 of file random.cpp.
void xint::clearbit (integer & n, size_t bit)
int xint::compare (const integer & b1, const integer & b2, bool ignoresign)
integer xint::divide (const integer & dividend, const integer & divisor)
Referenced by xint::integer::operator/=().
std::pair< integer, integer > xint::divide_r (const integer & d1, const integer & d2)
bool xint::exceptions_allowed ()
integer xint::factorial (size_t n)
integer xint::from_binary (const std::string & str)
integer xint::from_string (const std::string & str, size_t base)
Referenced by xint::integer::integer(), and operator>>().
integer xint::fromMontgomeryForm (const integer & n, const integer & m)
integer xint::gcd (const integer & num1, const integer & num2)
bool xint::getbit (const integer & n, size_t bit)
size_t xint::highestbit (const integer & n, size_t defaultValue)
detail::digit_t xint::inverse0 (const integer & n)
integer xint::invmod (const integer & n, const integer & m)
int xint::is_prime (const integer & n, callback_t callback)
integer xint::lcm (const integer & num1, const integer & num2)
size_t xint::log2 (const integer & n)
Referenced by xint::integer::hex_digits().
size_t xint::lowestbit (const integer & n, size_t defaultValue)
integer xint::mod (const integer & n, const integer & modBy)
Referenced by xint::integer::operator%=().
integer xint::montgomeryMultiplyMod (const integer & a, const integer & b, const integer & n, digit_t nPrime0)
integer xint::montgomeryPowerMod (const integer & a, const integer & e, const integer & n)
integer xint::montgomeryR (const integer & n)
integer xint::mulmod (const integer & n, const integer & by, const integer & modulus)
integer xint::multiply (const integer & n, const integer & by)
Referenced by xint::integer::operator*=().
integer xint::negate (const integer & _n)
Referenced by xint::integer::_set_negative().
bool xint::operator! (const xint::integer & num1)
bool xint::operator!= (const xint::integer & num1, const xint::integer & num2)
integer xint::operator% (const integer & num1, const integer & num2)
integer xint::operator& (const integer & n1, const integer & n2)
integer xint::operator* (const integer & num1, const integer & num2)
integer xint::operator+ (const integer & num1, const integer & num2)
const integer & xint::operator+ (const integer & a)
integer xint::operator- (const integer & num1, const integer & num2)
integer xint::operator- (const integer & a)
integer xint::operator/ (const integer & num1, const integer & num2)
bool xint::operator< (const xint::integer & num1, const xint::integer & num2)
template<typename charT , typename traits > std::basic_ostream<charT,traits>& xint::operator<< (std::basic_ostream< charT, traits > & out, const xint::integer & n) [inline]
Definition at line 397 of file xint.hpp.
References abs(), xint::integer::nan(), xint::detail::nan_text, xint::integer::sign(), and to_string().
bool xint::operator<= (const xint::integer & num1, const xint::integer & num2)
bool xint::operator== (const xint::integer & num1, const xint::integer & num2)
bool xint::operator> (const xint::integer & num1, const xint::integer & num2)
bool xint::operator>= (const xint::integer & num1, const xint::integer & num2)
template<typename charT , typename traits > std::basic_istream<charT,traits>& xint::operator>> (std::basic_istream< charT, traits > & in, xint::integer & n) [inline]
Definition at line 424 of file xint.hpp.
References allow_exceptions(), autobase, from_string(), and xint::detail::nan_text.
integer xint::operator^ (const integer & n1, const integer & n2)
integer xint::operator| (const integer & n1, const integer & n2)
bool xint::opt_secure_mode ()
bool xint::opt_thread_safe ()
integer xint::pow (const integer & n, const integer & exponent)
integer xint::pow2 (size_t exponent)
integer xint::powmod (const integer & n, const integer & exponent, const integer & modulus, bool noMontgomery)
integer xint::random_by_size (size_t bits, bool highBitOn, bool lowBitOn, bool canBeNegative)
integer xint::random_prime (size_t sizeInBits, callback_t callback)
template<typename T > void xint::set_random_generator (T & gen) [inline]
Definition at line 391 of file xint.hpp.
References xint::detail::set_random_generator().
void xint::setbit (integer & n, size_t bit)
integer xint::shift (const integer & n, int byBits)
integer xint::shift_left (const integer & _n, size_t byBits)
Referenced by xint::integer::operator<<().
integer xint::shift_right (const integer & _n, size_t byBits)
Referenced by xint::integer::operator>>().
integer xint::sqr (const integer & n)
integer xint::sqrmod (const integer & n, const integer & modulus)
integer xint::sqrt (const integer & n)
integer xint::subtract (const integer & n1, const integer & n2)
Referenced by xint::integer::operator-=().
bool xint::testAddSubtract ()
bool xint::testAll ()
bool xint::testBitManipulations ()
bool xint::testConvert ()
bool xint::testDivideMod ()
bool xint::testMontyMultiply ()
bool xint::testMontyPowerMod ()
bool xint::testMultiply ()
bool xint::testStreams ()
template<typename T > T xint::to (const integer & n) [inline]
Definition at line 375 of file xint.hpp.
References xint::integer::_get_digit(), xint::integer::_get_length(), xint::integer::_throw_if_nan(), xint::detail::digit_overflowbit, and xint::integer::sign().
std::string xint::to_binary (const integer & n)
std::string xint::to_string (const integer & n, size_t base, bool upperCase)
Referenced by operator<<().
integer xint::toMontgomeryForm (const integer & n, const integer & m)
Variable Documentation
const size_t xint::autobase = (std::numeric_limits<size_t>::max)()
Definition at line 79 of file xint.hpp.
Referenced by operator>>().
const callback_t xint::no_callback
Definition at line 77 of file xint.hpp.
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Wed Mar 31 15:44:54 2010