Quickbook Doxygen Index Prototype Tue Mar 30 18:10:43 2010 xInt eXtended Integer Library
-
I:/boost-sandbox/xInt/boost/xint/src/operators.cpp File Reference
#include "../xint.hpp"
Functions
const xint::integer & operator+ (const xint::integer &a)
xint::integer operator- (const xint::integer &a)
xint::integer operator+ (const xint::integer &num1, const xint::integer &num2)
xint::integer operator- (const xint::integer &num1, const xint::integer &num2)
xint::integer operator* (const xint::integer &num1, const xint::integer &num2)
xint::integer operator/ (const xint::integer &num1, const xint::integer &num2)
xint::integer operator% (const xint::integer &num1, const xint::integer &num2)
xint::integer operator& (const xint::integer &n1, const xint::integer &n2)
xint::integer operator| (const xint::integer &n1, const xint::integer &n2)
xint::integer operator^ (const xint::integer &n1, const xint::integer &n2)
Function Documentation
xint::integer operator% (const xint::integer & num1, const xint::integer & num2)
Definition at line 22 of file operators.cpp.
References xint::mod().
xint::integer operator& (const xint::integer & n1, const xint::integer & n2)
Definition at line 23 of file operators.cpp.
References xint::bitwise_and().
xint::integer operator* (const xint::integer & num1, const xint::integer & num2)
Definition at line 20 of file operators.cpp.
References xint::multiply().
xint::integer operator+ (const xint::integer & num1, const xint::integer & num2)
Definition at line 18 of file operators.cpp.
References xint::add().
const xint::integer& operator+ (const xint::integer & a)
Definition at line 16 of file operators.cpp.
xint::integer operator- (const xint::integer & num1, const xint::integer & num2)
Definition at line 19 of file operators.cpp.
References xint::subtract().
xint::integer operator- (const xint::integer & a)
Definition at line 17 of file operators.cpp.
References xint::negate().
xint::integer operator/ (const xint::integer & num1, const xint::integer & num2)
Definition at line 21 of file operators.cpp.
References xint::divide().
xint::integer operator^ (const xint::integer & n1, const xint::integer & n2)
Definition at line 25 of file operators.cpp.
References xint::bitwise_xor().
xint::integer operator| (const xint::integer & n1, const xint::integer & n2)
Definition at line 24 of file operators.cpp.
References xint::bitwise_or().
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright © 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Tue Mar 30 18:10:43 2010