Quickbook Doxygen Index Prototype Wed Mar 31 15:44:54 2010 xInt eXtended Integer Library
-
xint::detail::data_t Struct Reference
#include <xint_data_t.hpp>
Classes
struct QuickDigits
Public Member Functions
data_t (digit_t initial1=0, digit_t initial2=0, digit_t initial3=0)
data_t (data_t *c)
void attach ()
bool detach ()
void alloc (size_t digits, bool copydigits=false)
void realloc (size_t newdigits)
void skipLeadingZeros ()
void copy (const data_t *c, size_t extraDigits=0)
void zero (digit_t *p, size_t count)
void quickset (digit_t d1, digit_t d2=0, digit_t d3=0)
void invert ()
void negate ()
void add (const data_t &addend)
void subtract (const data_t &subtrahend)
void shift_left (size_t byBits)
void shift_right (size_t byBits)
Public Attributes
size_t mLength
size_t mAllocated
digit_t * digits
digit_t mQuickDigits [QuickDigits::count]
std::vector< digit_t > mStorage
int mCopies
bool mIsNegative
Detailed Description
Definition at line 32 of file xint_data_t.hpp.
Constructor & Destructor Documentation
xint::detail::data_t::data_t (digit_t initial1 = 0, digit_t initial2 = 0, digit_t initial3 = 0)
Definition at line 22 of file data_t.cpp.
References xint::detail::data_t::QuickDigits::count, digits, mAllocated, mCopies, mIsNegative, mLength, and mQuickDigits.
xint::detail::data_t::data_t (data_t * c)
Definition at line 33 of file data_t.cpp.
References xint::detail::data_t::QuickDigits::count, digits, mAllocated, mCopies, mIsNegative, mLength, mQuickDigits, and mStorage.
Member Function Documentation
void xint::detail::data_t::add (const data_t & addend)
Definition at line 198 of file data_t.cpp.
References xint::detail::digit_overflowbit, digits, mCopies, mLength, realloc(), and skipLeadingZeros().
Referenced by xint::integer::operator+=().
void xint::detail::data_t::alloc (size_t digits, bool copydigits = false)
Definition at line 85 of file data_t.cpp.
References xint::detail::data_t::QuickDigits::count, digits, mAllocated, mLength, mQuickDigits, mStorage, and zero().
Referenced by xint::integer::_init(), copy(), and realloc().
void xint::detail::data_t::attach () [inline]
Definition at line 59 of file xint_data_t.hpp.
References mCopies.
Referenced by xint::integer::_attach().
void xint::detail::data_t::copy (const data_t * c, size_t extraDigits = 0)
Definition at line 153 of file data_t.cpp.
References alloc(), digits, mIsNegative, and mLength.
bool xint::detail::data_t::detach () [inline]
Definition at line 60 of file xint_data_t.hpp.
References mCopies.
Referenced by xint::integer::_detach().
void xint::detail::data_t::invert ()
Definition at line 170 of file data_t.cpp.
References xint::detail::digit_overflowbit, digits, mCopies, mIsNegative, mLength, and skipLeadingZeros().
void xint::detail::data_t::negate ()
Definition at line 191 of file data_t.cpp.
References digits, mCopies, mIsNegative, and mLength.
Referenced by subtract().
void xint::detail::data_t::quickset (digit_t d1, digit_t d2 = 0, digit_t d3 = 0)
Definition at line 74 of file data_t.cpp.
References digits, mCopies, mIsNegative, mLength, and skipLeadingZeros().
void xint::detail::data_t::realloc (size_t newdigits) [inline]
Definition at line 62 of file xint_data_t.hpp.
References alloc().
Referenced by add(), and shift_left().
void xint::detail::data_t::shift_left (size_t byBits)
Definition at line 252 of file data_t.cpp.
References xint::detail::bits_per_digit, digits, mCopies, mLength, realloc(), and skipLeadingZeros().
Referenced by xint::integer::operator<<=().
void xint::detail::data_t::shift_right (size_t byBits)
Definition at line 280 of file data_t.cpp.
References xint::detail::bits_per_digit, digits, mCopies, mLength, and skipLeadingZeros().
Referenced by xint::integer::operator>>=().
void xint::detail::data_t::skipLeadingZeros ()
Definition at line 67 of file data_t.cpp.
References digits, mIsNegative, and mLength.
Referenced by xint::integer::_init(), add(), invert(), quickset(), shift_left(), shift_right(), and subtract().
void xint::detail::data_t::subtract (const data_t & subtrahend)
Definition at line 225 of file data_t.cpp.
References xint::detail::digit_overflowbit, digits, mCopies, mLength, negate(), and skipLeadingZeros().
Referenced by xint::integer::operator-=().
void xint::detail::data_t::zero (digit_t * p, size_t count)
Definition at line 165 of file data_t.cpp.
Referenced by alloc().
Member Data Documentation
digit_t* xint::detail::data_t::digits
Definition at line 42 of file xint_data_t.hpp.
Referenced by xint::integer::_get_digit(), xint::integer::_init(), add(), alloc(), copy(), data_t(), invert(), negate(), quickset(), shift_left(), shift_right(), skipLeadingZeros(), and subtract().
size_t xint::detail::data_t::mAllocated
Definition at line 41 of file xint_data_t.hpp.
Referenced by alloc(), and data_t().
int xint::detail::data_t::mCopies
Definition at line 48 of file xint_data_t.hpp.
Referenced by xint::integer::_make_unique(), add(), attach(), data_t(), detach(), invert(), negate(), quickset(), shift_left(), shift_right(), and subtract().
bool xint::detail::data_t::mIsNegative
Definition at line 49 of file xint_data_t.hpp.
Referenced by copy(), data_t(), invert(), negate(), quickset(), xint::integer::sign(), and skipLeadingZeros().
size_t xint::detail::data_t::mLength
Definition at line 41 of file xint_data_t.hpp.
Referenced by xint::integer::_get_length(), add(), alloc(), copy(), data_t(), invert(), negate(), xint::integer::operator+=(), quickset(), shift_left(), shift_right(), skipLeadingZeros(), and subtract().
digit_t xint::detail::data_t::mQuickDigits[QuickDigits::count]
Definition at line 42 of file xint_data_t.hpp.
Referenced by alloc(), and data_t().
std::vector<digit_t> xint::detail::data_t::mStorage
Definition at line 45 of file xint_data_t.hpp.
Referenced by alloc(), and data_t().
The documentation for this struct was generated from the following files:
I:/boost-sandbox/xInt/boost/xint/xint_data_t.hpp
I:/boost-sandbox/xInt/boost/xint/src/data_t.cpp
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright © 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Wed Mar 31 15:44:54 2010