Quickbook Doxygen Index Prototype Tue Mar 30 18:10:43 2010 xInt eXtended Integer Library
-
I:/boost-sandbox/xInt/boost/xint/xint.hpp File Reference
#include <string>
#include <limits>
#include <memory>
#include <cstddef>
#include <iostream>
#include <stdexcept>
#include <boost/integer.hpp>
#include <boost/cstdint.hpp>
#include <boost/function.hpp>
#include <boost/static_assert.hpp>
Classes
struct xint::detail::token
class xint::integer
class xint::invalid_base
class xint::invalid_digit
class xint::invalid_modulus
class xint::divide_by_zero
class xint::too_big
class xint::not_a_number
Namespaces
namespace xint
namespace for all extended integer classes and functions.
namespace xint::detail
implementation details, normal users should not need to use these.
Typedefs
typedef boost::uintmax_t xint::detail::doubledigit_t
typedef boost::uint_t
< std::numeric_limits
< doubledigit_t >::digits/2 >
::fast xint::detail::digit_t
typedef std::auto_ptr
< detail::token > xint::token
typedef boost::function< bool()> xint::callback_t
Functions
bool xint::exceptions_allowed ()
token xint::block_exceptions ()
token xint::allow_exceptions ()
bool xint::opt_secure_mode ()
bool xint::opt_thread_safe ()
int xint::compare (const integer &b1, const integer &b2, bool ignoresign)
size_t xint::log2 (const integer &n)
integer xint::gcd (const integer &num1, const integer &num2)
integer xint::lcm (const integer &num1, const integer &num2)
integer xint::abs (const integer &n)
integer xint::negate (const integer &_n)
integer xint::add (const integer &n1, const integer &n2)
integer xint::subtract (const integer &n1, const integer &n2)
integer xint::multiply (const integer &n, const integer &by)
integer xint::divide (const integer &dividend, const integer &divisor)
std::pair< integer, integer > xint::divide_r (const integer &d1, const integer &d2)
integer xint::sqr (const integer &n)
integer xint::pow (const integer &n, const integer &exponent)
integer xint::pow2 (size_t exponent)
integer xint::factorial (size_t n)
integer xint::sqrt (const integer &n)
template<typename T >
T xint::to (const integer &n)
std::string xint::to_string (const integer &n, size_t base, bool upperCase)
integer xint::from_string (const std::string &str, size_t base)
std::string xint::to_binary (const integer &n)
integer xint::from_binary (const std::string &str)
bool xint::getbit (const integer &n, size_t bit)
void xint::setbit (integer &n, size_t bit)
void xint::clearbit (integer &n, size_t bit)
size_t xint::lowestbit (const integer &n, size_t defaultValue)
size_t xint::highestbit (const integer &n, size_t defaultValue)
integer xint::bitwise_and (const integer &n1, const integer &n2)
integer xint::bitwise_or (const integer &n1, const integer &n2)
integer xint::bitwise_xor (const integer &n1, const integer &n2)
integer xint::shift (const integer &n, int byBits)
integer xint::shift_left (const integer &_n, size_t byBits)
integer xint::shift_right (const integer &_n, size_t byBits)
integer xint::mod (const integer &n, const integer &modBy)
integer xint::mulmod (const integer &n, const integer &by, const integer &modulus)
integer xint::sqrmod (const integer &n, const integer &modulus)
integer xint::powmod (const integer &n, const integer &exponent, const integer &modulus, bool noMontgomery)
integer xint::invmod (const integer &n, const integer &m)
bool xint::seed_secure ()
void xint::seed_fallback ()
void xint::seed_manual (const std::string &value)
integer xint::random_by_size (size_t bits, bool highBitOn, bool lowBitOn, bool canBeNegative)
template<typename T >
T xint::random ()
template<typename T >
T xint::random (const T &lessThanThis)
template<typename T >
T xint::random (const T &lowest, const T &highest)
int xint::is_prime (const integer &n, callback_t callback)
integer xint::random_prime (size_t sizeInBits, callback_t callback)
bool operator! (const xint::integer &n1)
bool operator< (const xint::integer &n1, const xint::integer &n2)
bool operator> (const xint::integer &n1, const xint::integer &n2)
bool operator<= (const xint::integer &n1, const xint::integer &n2)
bool operator>= (const xint::integer &n1, const xint::integer &n2)
bool operator== (const xint::integer &n1, const xint::integer &n2)
bool operator!= (const xint::integer &n1, const xint::integer &n2)
const xint::integer & operator+ (const xint::integer &a)
xint::integer operator- (const xint::integer &a)
xint::integer operator+ (const xint::integer &n1, const xint::integer &n2)
xint::integer operator- (const xint::integer &n1, const xint::integer &n2)
xint::integer operator* (const xint::integer &n1, const xint::integer &n2)
xint::integer operator/ (const xint::integer &n1, const xint::integer &n2)
xint::integer operator% (const xint::integer &n1, const xint::integer &n2)
xint::integer operator& (const xint::integer &n1, const xint::integer &n2)
xint::integer operator| (const xint::integer &n1, const xint::integer &n2)
xint::integer operator^ (const xint::integer &n1, const xint::integer &n2)
template<>
integer xint::random< integer > (const integer &lowest, const integer &highest)
template<typename charT , typename traits >
std::basic_ostream< charT,
traits > & xint::operator<< (std::basic_ostream< charT, traits > &out, const xint::integer &n)
template<typename charT , typename traits >
std::basic_istream< charT,
traits > & xint::operator>> (std::basic_istream< charT, traits > &in, xint::integer &n)
Variables
const size_t xint::detail::bits_per_digit = std::numeric_limits<digit_t>::digits
const digit_t xint::detail::digit_hibit = (digit_t(1) << (bits_per_digit-1))
const doubledigit_t xint::detail::doubledigit_hibit = (doubledigit_t(1) << (bits_per_digit*2-1))
const doubledigit_t xint::detail::digit_overflowbit = (doubledigit_t(1) << bits_per_digit)
const digit_t xint::detail::digit_mask = digit_t(digit_overflowbit-1)
const std::string xint::detail::nan_text
const callback_t xint::no_callback
const size_t xint::autobase = (std::numeric_limits<size_t>::max)()
Function Documentation
bool operator! (const xint::integer & n1)
Definition at line 54 of file compare.cpp.
References xint::integer::sign().
bool operator!= (const xint::integer & n1, const xint::integer & n2)
Definition at line 56 of file compare.cpp.
References xint::compare().
xint::integer operator% (const xint::integer & n1, const xint::integer & n2)
Definition at line 22 of file operators.cpp.
References xint::mod().
xint::integer operator& (const xint::integer & n1, const xint::integer & n2)
Definition at line 23 of file operators.cpp.
References xint::bitwise_and().
xint::integer operator* (const xint::integer & n1, const xint::integer & n2)
Definition at line 20 of file operators.cpp.
References xint::multiply().
xint::integer operator+ (const xint::integer & n1, const xint::integer & n2)
Definition at line 18 of file operators.cpp.
References xint::add().
const xint::integer& operator+ (const xint::integer & a)
Definition at line 16 of file operators.cpp.
xint::integer operator- (const xint::integer & n1, const xint::integer & n2)
Definition at line 19 of file operators.cpp.
References xint::subtract().
xint::integer operator- (const xint::integer & a)
Definition at line 17 of file operators.cpp.
References xint::negate().
xint::integer operator/ (const xint::integer & n1, const xint::integer & n2)
Definition at line 21 of file operators.cpp.
References xint::divide().
bool operator< (const xint::integer & n1, const xint::integer & n2)
Definition at line 57 of file compare.cpp.
References xint::compare().
bool operator<= (const xint::integer & n1, const xint::integer & n2)
Definition at line 59 of file compare.cpp.
References xint::compare().
bool operator== (const xint::integer & n1, const xint::integer & n2)
Definition at line 55 of file compare.cpp.
References xint::compare().
bool operator> (const xint::integer & n1, const xint::integer & n2)
Definition at line 58 of file compare.cpp.
References xint::compare().
bool operator>= (const xint::integer & n1, const xint::integer & n2)
Definition at line 60 of file compare.cpp.
References xint::compare().
xint::integer operator^ (const xint::integer & n1, const xint::integer & n2)
Definition at line 25 of file operators.cpp.
References xint::bitwise_xor().
xint::integer operator| (const xint::integer & n1, const xint::integer & n2)
Definition at line 24 of file operators.cpp.
References xint::bitwise_or().
-
Use, modification and distribution are subject to the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Copyright 2009 - 2010 Chad Nelson, Oak Circle Software, Inc
Doxygen Documentation generated by 1.6.3, Revised at Tue Mar 30 18:10:43 2010