// Visual Age (IBM) C++ compiler setup:

#define BOOST_NO_MEMBER_TEMPLATE_FRIENDS
#define BOOST_NO_INCLASS_MEMBER_INITIALIZATION

#define BOOST_COMPILER "IBM Visual Age" BOOST_STRINGIZE(__IBMCPP__)

 
