namespace boost {

/** \mainpage

This is generated by doxygen directly.

It includes things such as a \ref page_related, <a href="modules.html">modules/groups</a>, automatically
generated \ref todo and \ref bug.
*/

/** \page page_related Related Page
This is a doxygen related page.
*/

/** \defgroup group_nothing Classes that do nothing.
This group contains classes that do nothing.
*/

}