#ifndef BOOST_LANGBINDING_FUNCTION_CONFIG_040916_HPP
#define BOOST_LANGBINDING_FUNCTION_CONFIG_040916_HPP

# ifndef BOOST_LANGBINDING_FUNCTION_MAX_ARITY
#  define BOOST_LANGBINDING_FUNCTION_MAX_ARITY 5
# endif

#endif // BOOST_LANGBINDING_FUNCTION_CONFIG_040916_HPP

