//  (C) Copyright 2009-2011 Frederic Bron.
//  Use, modification and distribution are subject to the
//  Boost Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#include "test.hpp"
#include "check_integral_constant.hpp"

#include <boost/type_traits/can_call.hpp>
#include "can_call_binary_classes.hpp"

TT_TEST_BEGIN(BOOST_TT_TRAIT_NAME)
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C518 &, C518, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C518 &, C518 const &, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C518 const volatile &, C518 const volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C519 const, C519 volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C519 volatile, C519 volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C519 volatile, C519 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C519 volatile &, C519 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 const, C520, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 const, C520 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 &, C520 const volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 const &, C520 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 const &, C520 volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C520 const volatile &, C520 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C521 &, C521 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C521 const &, C521 &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C522 const, C522 &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C522 const &, C522 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C522 const volatile &, C522 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C523 const, C523 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C523 const volatile, C523 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C523 &, C523 volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C523 &, C523 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C523 const &, C523 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C524, C524 const volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C524, C524 &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C524 volatile, C524 const volatile &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C524 const &, C524 volatile, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C525, C525 volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C525 const, C525 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C525 volatile, C525, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C525 volatile, C525 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C525 const volatile &, C525 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C526 volatile, C526 const volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C526 &, C526 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C526 &, C526 const &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C526 &, C526 volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C526 const volatile &, C526 const volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C527 volatile, C527 &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528, C528 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528, C528 const &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 volatile, C528, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 volatile, C528, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 volatile, C528, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 volatile, C528 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 const volatile, C528 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 const volatile, C528 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 const volatile &, C528, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 const volatile &, C528 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C528 const volatile &, C528 const volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C529 volatile, C529 const volatile, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C529 const volatile, C529 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C529 const volatile &, C529 &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C530 const volatile, C530 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C530 const volatile &, C530 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C530 const volatile &, C530 const volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C531 const, C531 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C531 volatile, C531 const volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C531 const volatile, C531, void >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C531 &, C531 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C531 const &, C531 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 const, C532 const volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 const, C532 volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 volatile, C532 const volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 const volatile, C532 const volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 &, C532 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 const &, C532 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C532 volatile &, C532 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C533, C533, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C533, C533 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C533 volatile, C533 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C533 const &, C533 &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C533 const volatile &, C533 const volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C534, C534 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C534 &, C534 const &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C534 &, C534 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C534 volatile &, C534 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C535 const, C535 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C535 volatile, C535, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C535 volatile, C535 const, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C535 &, C535, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536, C536 const volatile &, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536 const, C536 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536 const, C536 &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536 const &, C536 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536 volatile &, C536, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C536 const volatile &, C536, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537, C537 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537 const, C537 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537 volatile, C537, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537 volatile, C537 const volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537 const &, C537 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C537 const volatile &, C537 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538, C538 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 volatile, C538 volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 &, C538 const volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 &, C538 volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 const &, C538 volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 const &, C538 const &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C538 const volatile &, C538 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C539 const, C539 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C539 const volatile, C539 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C539 const volatile, C539 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C539 const &, C539 const &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C540, C540 const volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C540 const volatile, C540 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C540 &, C540 volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C541, C541 const &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C541 const volatile, C541 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C541 const &, C541, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C541 const &, C541 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C542 const, C542 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C542 const volatile &, C542 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C543 volatile, C543 const &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C543 volatile, C543 const volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C543 const volatile, C543 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C543 &, C543 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C543 const &, C543 volatile, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C544, C544 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C544 &, C544 volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C544 const &, C544 const &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C544 volatile &, C544 const, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C545, C545 const &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C545 &, C545 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C546 const, C546 volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C546 const, C546 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C546 const &, C546 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C546 volatile &, C546 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C546 const volatile &, C546 const, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile, C547, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile, C547 const volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const &, C547 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile &, C547, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile &, C547 volatile, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile &, C547 const volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C547 const volatile &, C547 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C548, C548 const volatile, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C548, C548 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C548 const &, C548 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 const, C549, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 const, C549 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 const, C549 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 volatile, C549 volatile &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 volatile, C549 const volatile &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 &, C549, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 &, C549 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C549 volatile &, C549 const, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550, C550 volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550 const, C550, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550 volatile, C550 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550 const volatile, C550 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550 const volatile, C550 const, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C550 volatile &, C550 const &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C551 &, C551 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 const volatile, C552 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 &, C552, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 &, C552 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 const &, C552 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 volatile &, C552 const &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C552 const volatile &, C552 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C553 const volatile, C553 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C554, C554 const volatile, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C554 volatile &, C554 const &, ret & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C555, C555 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C555 const, C555 const volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C555 const volatile, C555 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C555 const &, C555 volatile &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C555 const volatile &, C555 const, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C556, C556 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C556 volatile, C556 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C556 const volatile &, C556 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557, C557 const volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557 const, C557, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557 &, C557 const volatile, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557 const &, C557, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557 const &, C557 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C557 volatile &, C557 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C558 volatile, C558 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C558 const volatile &, C558 volatile &, void >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C559 volatile, C559 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C559 const &, C559 const, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C560 &, C560 const &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C560 const volatile &, C560 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C561 const, C561 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C561 const volatile, C561, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C561 const volatile, C561 const, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C561 const &, C561 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C562, C562 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C562 const, C562 volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C562 const, C562 const volatile &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C562 volatile, C562 volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C562 const volatile &, C562 volatile, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563, C563 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563 const, C563 volatile &, ret & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563 volatile, C563 volatile, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563 volatile, C563 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563 const volatile, C563 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C563 &, C563 const volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C564 const volatile, C564 const &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C564 &, C564 volatile &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 const, C565 volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 const volatile, C565 const &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 &, C565 const volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 const &, C565 volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 volatile &, C565 const volatile &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C565 const volatile &, C565 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566, C566 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566 const volatile, C566, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566 const volatile, C566 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566 const volatile, C566 const volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566 volatile &, C566 &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C566 const volatile &, C566 const volatile &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C567, C567 const volatile &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C567 const volatile, C567 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568, C568, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568, C568 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568, C568 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 const, C568 &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 const, C568 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 volatile, C568 const volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 const volatile, C568 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 const volatile, C568 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C568 const &, C568, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C569 const volatile &, C569 const volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570, C570 &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 const, C570 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 const, C570 const &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 volatile, C570 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 const volatile, C570, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 &, C570 const volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 const &, C570 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C570 const volatile &, C570 volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 volatile, C571, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 const volatile, C571 &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 &, C571 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 &, C571 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 const &, C571 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 const &, C571 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C571 volatile &, C571 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C572 const, C572 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C572 volatile, C572 const volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C572 &, C572 const volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C572 volatile &, C572 const &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C573 volatile, C573 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C573 &, C573, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C573 volatile &, C573, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C573 const volatile &, C573 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C574 const, C574 volatile &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C575 volatile, C575 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C575 &, C575 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C575 const &, C575 const volatile, ret volatile >::value), 1);
TT_TEST_END
