//  (C) Copyright 2009-2011 Frederic Bron.
//  Use, modification and distribution are subject to the
//  Boost Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#include "test.hpp"
#include "check_integral_constant.hpp"

#include <boost/type_traits/can_call.hpp>
#include "can_call_binary_classes.hpp"

TT_TEST_BEGIN(BOOST_TT_TRAIT_NAME)
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000, C000 const, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000, C000 const &, void >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000, C000 const &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 const, C000 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 volatile, C000 const volatile &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 volatile, C000 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 const volatile, C000 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 &, C000 const volatile, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 &, C000 &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 &, C000 const &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C000 const &, C000, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C001 volatile, C001 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C001 const volatile, C001 &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C001 const volatile, C001 &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C001 const volatile &, C001 volatile, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C002, C002 &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C002 const, C002 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C002 const &, C002, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C002 volatile &, C002, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C003, C003 volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C003 const volatile &, C003, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C004, C004, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C004 volatile, C004 volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C004 &, C004 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C004 const &, C004 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C005, C005 const volatile &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C005 volatile, C005 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C005 &, C005 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C005 &, C005 const volatile &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C005 volatile &, C005 const &, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C006 const &, C006 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C006 const volatile &, C006 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 const, C007 &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 const, C007 volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 const volatile, C007 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 const volatile, C007 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 volatile &, C007 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C007 volatile &, C007 &, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008, C008, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 const, C008 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 volatile, C008 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 &, C008, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 &, C008 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 volatile &, C008 const &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C008 const volatile &, C008 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C009, C009 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C009 volatile &, C009 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C009 const volatile &, C009 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C010, C010 const volatile, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C010, C010 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C010 const, C010 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C010 const &, C010, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C010 const volatile &, C010 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011, C011 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011, C011 const volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011 const volatile, C011, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011 const volatile, C011 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011 const &, C011 volatile, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011 volatile &, C011, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C011 const volatile &, C011 &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C012, C012 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C012, C012 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C012 volatile, C012 const &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C012 const &, C012 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C013, C013 const, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C013 const volatile, C013 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C013 const volatile &, C013 const, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C014, C014, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C014 volatile &, C014, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C014 const volatile &, C014, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C015, C015 const &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C015 const, C015 volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C015 &, C015 volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C015 &, C015 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C015 const volatile &, C015 volatile, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C016 const, C016 const volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C016 const volatile, C016 const, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C017 const volatile &, C017 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C018, C018 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C018 const volatile, C018 const volatile, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C018 &, C018 &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C018 const volatile &, C018 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C019 const, C019 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C019 const, C019 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C019 const volatile, C019, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C019 &, C019 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C019 &, C019 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020, C020, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020, C020 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020, C020 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020 volatile, C020 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020 volatile &, C020, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C020 const volatile &, C020 const &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C021, C021 volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C021 &, C021, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C021 &, C021, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C021 &, C021 const volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C021 &, C021 &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C022 const volatile, C022, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C022 &, C022 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C022 const &, C022 const &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C023 volatile &, C023 volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C024 const, C024 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C024 const, C024 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025, C025 volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 const, C025 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 volatile, C025 const &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 volatile, C025 const &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 const volatile, C025 const &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 const volatile, C025 const volatile &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 const &, C025 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C025 const volatile &, C025 volatile, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026, C026 const volatile, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 const, C026 const volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 volatile, C026 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 const volatile, C026 const &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 &, C026 &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 const &, C026 volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C026 const volatile &, C026 const volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C027 volatile, C027 const volatile, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C028 const, C028 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C028 volatile, C028 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C028 const volatile, C028 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C028 volatile &, C028 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C028 const volatile &, C028 const &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029, C029 volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const, C029 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 volatile, C029 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const volatile, C029 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const volatile, C029 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 &, C029, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 &, C029 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const &, C029, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const &, C029 const volatile, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 const &, C029 const volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 volatile &, C029 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C029 volatile &, C029 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C030 const, C030, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C030 volatile, C030 const &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C030 &, C030 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C030 const &, C030 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031, C031 const, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031 const, C031 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031 const, C031 const volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031 const volatile, C031 const &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031 volatile &, C031 const volatile &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C031 const volatile &, C031 const volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C032 volatile, C032 const volatile, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C032 &, C032 const, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C032 volatile &, C032 const volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 volatile, C033 const, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 const volatile, C033 const, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 &, C033 const, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 const &, C033, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 volatile &, C033 const volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 volatile &, C033 &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C033 volatile &, C033 volatile &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C034 const, C034 const volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C034 const volatile, C034 const, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C034 const volatile, C034 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C034 volatile &, C034 const, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C034 volatile &, C034 volatile &, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035, C035 const, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035, C035 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035, C035 volatile &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 volatile, C035, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 volatile, C035 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 volatile, C035 const volatile &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 const &, C035 const volatile, ret const volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 volatile &, C035 volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C035 volatile &, C035 const volatile &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C036 volatile, C036 &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C036 const volatile, C036, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C036 const volatile, C036 const &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C036 volatile &, C036 const volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C036 const volatile &, C036 const &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C037 volatile &, C037 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C038 volatile, C038 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C038 const volatile, C038 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C038 const volatile, C038 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C038 const volatile &, C038 volatile &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039, C039 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039 const, C039 &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039 &, C039 const volatile, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039 &, C039 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039 volatile &, C039, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C039 const volatile &, C039 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040, C040, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 const, C040 const, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 volatile, C040 const volatile, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 const volatile, C040 volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 const volatile, C040 const volatile &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 volatile &, C040 volatile, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C040 volatile &, C040 const &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 volatile, C041 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 volatile, C041 const &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 volatile, C041 volatile &, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 const volatile, C041 volatile &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 const volatile, C041 volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C041 const volatile &, C041, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 volatile, C043 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 &, C043 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 const &, C043 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 volatile &, C043 volatile &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 const volatile &, C043 const volatile, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 const volatile &, C043 &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C043 const volatile &, C043 const &, ret const >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C044 const volatile, C044 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C045, C045 const volatile, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C045 volatile, C045 volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C045 const volatile, C045 &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C046 volatile, C046 volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C046 const volatile, C046 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C046 &, C046 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C047, C047 volatile, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C047 const &, C047 const &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C048 const, C048 volatile, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C048 &, C048, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C048 &, C048 const &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C048 const &, C048 const volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C049 volatile &, C049 const, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050, C050 const volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 const, C050, ret volatile & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 volatile, C050 volatile &, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 volatile, C050 volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 &, C050 &, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 const &, C050 volatile &, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C050 const volatile &, C050 volatile, ret const volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C051 const, C051, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C051 const, C051 const volatile &, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C052 const, C052 const &, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C052 volatile, C052 const volatile, ret >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C052 &, C052 &, ret const >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C052 const volatile &, C052 &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C053 &, C053, ret >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C053 volatile &, C053 const volatile, ret volatile >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C053 volatile &, C053 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C054, C054 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C054 volatile, C054 const, ret const & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C054 const volatile &, C054 const &, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C054 const volatile &, C054 const volatile &, ret volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055, C055 &, ret & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055, C055 &, ret const & >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 const, C055 volatile, void >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 &, C055 volatile, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 &, C055 const volatile &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 const &, C055 &, ret const volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 volatile &, C055 const &, ret const volatile & >::value), 0);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 const volatile &, C055, ret volatile >::value), 1);
   BOOST_CHECK_INTEGRAL_CONSTANT((::boost::can_call_addition< C055 const volatile &, C055 const, ret const volatile & >::value), 0);
TT_TEST_END
