#ifndef SIGNAL_NETWORK_TEMPLATE_BODY
	SIGNAL_NETWORK_FUNCTION(SIGNAL_NETWORK_DEFAULT_SLOT,Signature,SIGNAL_NETWORK_TEMPLATE_ARITY)
		{
			boost::mutex::scoped_lock lock(mutex_);
			SIGNAL_NETWORK_RETURN(_return) SIGNAL_NETWORK_TEMPLATE_BASE::out(SIGNAL_NETWORK_ARG_NAMES(SIGNAL_NETWORK_TEMPLATE_ARITY));
		}
	private:
		boost::mutex mutex_;
#else

#endif
