CXX=g++
CXXFLAGS=-pedantic -W -Wall -I.
#CXXFLAGS=-pedantic -W -Wall -I${BOOST} -I.

LD=g++

TARGET=dbg_exc_mt

PACKAGE_OBJECTS=backward_hds_concept_archetype.o \
        bidirectional_hds_concept_archetype.o \
        facet_hds_concept_archetype.o \
        facet_list_hds_concept_archetype.o \
        forward_hds_concept_archetype.o \
        hds_concept_archetype.o \
        halfedge_list_hds_concept_archetype.o \
        mutable_forward_hds_concept_archetype.o \
        mutable_backward_hds_concept_archetype.o \
        mutable_bidirectional_hds_concept_archetype.o \
        mutable_hds_concept_archetype.o \
        mutable_facet_hds_concept_archetype.o \
        mutable_vertex_hds_concept_archetype.o \
        vertex_hds_concept_archetype.o \
        vertex_list_hds_concept_archetype.o

PACKAGE_LIBRARY=libhds_archetypes.a

TEST_DRIVERS=backward_hds_concept_archetype.t \
        bidirectional_hds_concept_archetype.t \
        facet_hds_concept_archetype.t \
        facet_list_hds_concept_archetype.t \
        forward_hds_concept_archetype.t \
        hds_concept_archetype.t \
        halfedge_list_hds_concept_archetype.t \
        mutable_forward_hds_concept_archetype.t \
        mutable_backward_hds_concept_archetype.t \
        mutable_bidirectional_hds_concept_archetype.t \
        mutable_hds_concept_archetype.t \
        mutable_facet_hds_concept_archetype.t \
        mutable_vertex_hds_concept_archetype.t \
        vertex_hds_concept_archetype.t \
        vertex_list_hds_concept_archetype.t

.SUFFIXES:
.SUFFIXES: ${TARGET}.o .o .cpp .hpp

all: package_library test


### BUILDING PACKAGE LIBRARY AND DEPENDENCIES

package_library: ${PACKAGE_OBJECTS}
	ar -rv ${PACKAGE_LIBRARY} ${PACKAGE_OBJECTS}

%.o: %.cpp %.h
	${CXX} ${CXXFLAGS} ${CXXINCLUDES} -c -o $*.o $<

backward_hds_concept.o: hds_concept.hpp
bidirectional_hds_concept.o: forward_hds_concept.hpp \
        backward_hds_concept.hpp hds_concept.hpp
facet_hds_concept.o: hds_concept.hpp
forward_hds_concept.o: hds_concept.hpp  
hds_concept.o: 
halfedge_list_hds_concept.o: hds_concept.hpp
mutable_forward_hds_concept.o: forward_hds_concept.hpp \
        hds_concept.hpp mutable_hds_concept.hpp
mutable_backward_hds_concept.o: backward_hds_concept.hpp \
        hds_concept.hpp mutable_hds_concept.hpp
mutable_bidirectional_hds_concept.o: mutable_forward_hds_concept.hpp \
        mutable_backward_hds_concept.hpp  hds_concept.hpp \
		mutable_hds_concept.hpp
mutable_hds_concept.o: hds_concept.hpp
mutable_facet_hds_concept.o: facet_hds_concept.hpp \
        mutable_hds_concept.hpp
mutable_vertex_hds_concept.o: vertex_hds_concept.hpp \
        mutable_hds_concept.hpp
vertex_hds_concept.o: hds_concept.hpp
vertex_list_hds_concept.o: vertex_hds_concept.hpp

### BUILDING TEST DRIVERS AND DEPENDENCIES OF TEST DRIVER

test: ${TEST_DRIVERS}
	for file in ${TEST_DRIVERS}; do echo "******* TESTING $$file *********"; ./$$file; done

%.t: %.t.o %.o
	${LD} ${LDFLAGS} -o $*.t $^

backward_hds_concept_archetype.t.o: hds_concept_archetype.hpp
bidirectional_hds_concept_archetype.t.o: forward_hds_concept_archetype.hpp \
        backward_hds_concept_archetype.hpp hds_concept_archetype.hpp
facet_hds_concept_archetype.t.o: hds_concept_archetype.hpp
facet_list_hds_concept_archetype.t.o: hds_concept_archetype.hpp \
		facet_hds_concept_archetype.hpp
forward_hds_concept_archetype.t.o: hds_concept_archetype.hpp  
hds_concept_archetype.t.o: 
halfedge_list_hds_concept_archetype.t.o: hds_concept_archetype.hpp
mutable_forward_hds_concept_archetype.t.o: forward_hds_concept_archetype.hpp \
        hds_concept_archetype.hpp mutable_hds_concept_archetype.hpp
mutable_backward_hds_concept_archetype.t.o: backward_hds_concept_archetype.hpp \
        hds_concept_archetype.hpp mutable_hds_concept_archetype.hpp
mutable_bidirectional_hds_concept_archetype.t.o: mutable_forward_hds_concept_archetype.hpp \
        mutable_backward_hds_concept_archetype.hpp hds_concept_archetype.hpp \
		mutable_hds_concept_archetype.hpp
mutable_hds_concept_archetype.t.o: hds_concept_archetype.hpp
mutable_facet_hds_concept_archetype.t.o: facet_hds_concept_archetype.hpp \
        mutable_hds_concept_archetype.hpp
mutable_vertex_hds_concept_archetype.t.o: vertex_hds_concept_archetype.hpp \
        mutable_hds_concept_archetype.hpp
vertex_hds_concept_archetype.t.o: hds_concept_archetype.hpp
vertex_list_hds_concept_archetype.t.o: vertex_hds_concept_archetype.hpp

%.t.o: %.t.cpp %.h
	${CXX}  ${CXXFLAGS} ${CXXINCLUDES} -c -o $*.t.o $<

backward_hds_concept.t: hds_concept.o
bidirectional_hds_concept.t: forward_hds_concept.o \
        backward_hds_concept.o hds_concept.o
facet_hds_concept.t.o: hds_concept.o
facet_list_hds_concept.t.o: hds_concept.o \
		facet_hds_concept.o
forward_hds_concept.t.o: hds_concept.o  
hds_concept.t.o: 
halfedge_list_hds_concept.t.o: hds_concept.o
mutable_forward_hds_concept.t.o: forward_hds_concept.o \
        hds_concept.o mutable_hds_concept.o
mutable_backward_hds_concept.t.o: backward_hds_concept.o \
        hds_concept.o mutable_hds_concept.o
mutable_bidirectional_hds_concept.t.o: mutable_forward_hds_concept.hpp \
        mutable_backward_hds_concept.o  hds_concept.o \
		mutable_hds_concept.o
mutable_hds_concept.t.o: hds_concept.o
mutable_facet_hds_concept.o: facet_hds_concept.o \
        mutable_hds_concept.o
mutable_vertex_hds_concept.o: vertex_hds_concept.o \
        mutable_hds_concept.o
vertex_hds_concept.t.o: hds_concept.o
vertex_list_hds_concept.t.o: vertex_hds_concept.o

## UTILITIES

clean: testclean

testclean:
	- rm *.t.o
	- rm *.t

realclean:
	- rm *.o
	- rm ${PACKAGE_LIBRARY}

