Import("env")
import os

module = env.SharedLibrary("test_mod", "test_mod.cpp", SHLIBPREFIX="")
path = os.path.abspath(os.curdir)
runs = [env.Command(".%s" % script, [module, script], "python %s" % os.path.join(path,script)) 
        for script in ("test_script.py",)]
test = Alias("test", [runs])
