Import("bp_extensions_env")

test_mod = bp_extensions_env.SharedLibrary("test_mod", "test_mod.cpp", SHLIBPREFIX="")
test = bp_extensions_env.PythonUnitTest("test_script.py", test_mod)

Return("test")
