// Copyright (C) 2005 Peder Holt
// Use, modification and distribution is subject to the Boost Software
// License, Version 1.0. (http://www.boost.org/LICENSE_1_0.txt)

#include <boost/detail/workaround.hpp>
#include <boost/config.hpp>

#ifndef BOOST_METAMATHMATH_DOUBLE_DOUBLE_MACROS_HPP
#define BOOST_METAMATHMATH_DOUBLE_DOUBLE_MACROS_HPP

#define BOOST_METAMATH_EXP512 1.3407807929942597099574024998206e+154
#define BOOST_METAMATH_EXP256 1.1579208923731619542357098500869e+77
#define BOOST_METAMATH_EXP128 3.4028236692093846346337460743177e+38
#define BOOST_METAMATH_EXP64 18446744073709551616.0
#define BOOST_METAMATH_EXP32 4294967296.0
#define BOOST_METAMATH_EXP31 2147483648.0
#define BOOST_METAMATH_EXP30 1073741824.0
#define BOOST_METAMATH_EXP16 65536.0
#define BOOST_METAMATH_EXP8 256.0
#define BOOST_METAMATH_EXP4 16.0
#define BOOST_METAMATH_EXP2 4.0
#define BOOST_METAMATH_EXP1 2.0
#define BOOST_METAMATH_EXP0 1.0
#define BOOST_METAMATH_EXP_1 0.5
#define BOOST_METAMATH_EXP_2 0.25
#define BOOST_METAMATH_EXP_4 0.0625
#define BOOST_METAMATH_EXP_8 0.00390625
#define BOOST_METAMATH_EXP_16 0.0000152587890625
#define BOOST_METAMATH_EXP_32 0.00000000023283064365386962890625
#define BOOST_METAMATH_EXP_64 5.4210108624275221700372640043497e-20
#define BOOST_METAMATH_EXP_128 2.9387358770557187699218413430556e-39
#define BOOST_METAMATH_EXP_256 8.6361685550944446253863518628004e-78
#define BOOST_METAMATH_EXP_512 7.4583407312002067432909653154629e-155

//Normalise double (remove exponent)
#define BOOST_METAMATH_REMOVE_SIGN(value) (value)* (value<0?-1.:1.)
//Positive exponents
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP512(value) BOOST_METAMATH_REMOVE_SIGN(value) * (BOOST_METAMATH_REMOVE_SIGN(value)>BOOST_METAMATH_EXP512? BOOST_METAMATH_EXP_512 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP256(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP512(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP512(value)>BOOST_METAMATH_EXP256? BOOST_METAMATH_EXP_256 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP128(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP256(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP256(value)>BOOST_METAMATH_EXP128? BOOST_METAMATH_EXP_128 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP64(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP128(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP128(value)>BOOST_METAMATH_EXP64? BOOST_METAMATH_EXP_64 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP32(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP64(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP64(value)>BOOST_METAMATH_EXP32?BOOST_METAMATH_EXP_32 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP16(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP32(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP32(value)>BOOST_METAMATH_EXP16?BOOST_METAMATH_EXP_16 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP8(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP16(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP16(value)>BOOST_METAMATH_EXP8?BOOST_METAMATH_EXP_8 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP4(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP8(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP8(value)>BOOST_METAMATH_EXP4?BOOST_METAMATH_EXP_4 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP2(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP4(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP4(value)>BOOST_METAMATH_EXP2?BOOST_METAMATH_EXP_2 : 1.)
#define BOOST_METAMATH_REMOVE_POSITIVE_EXP1(value) BOOST_METAMATH_REMOVE_POSITIVE_EXP2(value) * (BOOST_METAMATH_REMOVE_POSITIVE_EXP2(value)>BOOST_METAMATH_EXP1?BOOST_METAMATH_EXP_1 : 1.)
//Negative exponents
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP512(value) BOOST_METAMATH_REMOVE_SIGN(value) * (BOOST_METAMATH_REMOVE_SIGN(value)<BOOST_METAMATH_EXP_512 *2.? BOOST_METAMATH_EXP512 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP256(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP512(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP512(value)<BOOST_METAMATH_EXP_256 *2.? BOOST_METAMATH_EXP256 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP128(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP256(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP256(value)<BOOST_METAMATH_EXP_128 *2.? BOOST_METAMATH_EXP128 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP64(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP128(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP128(value)<BOOST_METAMATH_EXP_64 *2.? BOOST_METAMATH_EXP64 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP32(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP64(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP64(value)<BOOST_METAMATH_EXP_32 *2.?BOOST_METAMATH_EXP32 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP16(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP32(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP32(value)<BOOST_METAMATH_EXP_16 *2.?BOOST_METAMATH_EXP16 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP8(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP16(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP16(value)<BOOST_METAMATH_EXP_8 *2.?BOOST_METAMATH_EXP8 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP4(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP8(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP8(value)<BOOST_METAMATH_EXP_4 *2.?BOOST_METAMATH_EXP4 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP2(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP4(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP4(value)<BOOST_METAMATH_EXP_2 *2.?BOOST_METAMATH_EXP2 : 1.)
#define BOOST_METAMATH_REMOVE_NEGATIVE_EXP1(value) BOOST_METAMATH_REMOVE_NEGATIVE_EXP2(value) * (BOOST_METAMATH_REMOVE_NEGATIVE_EXP2(value)<BOOST_METAMATH_EXP_1 *2.?BOOST_METAMATH_EXP1 : 1.)

#define BOOST_METAMATH_HAS_NEGATIVE_EXP(value) (value<1. && value>-1.)
#define BOOST_METAMATH_NORMALISE(value) (BOOST_METAMATH_HAS_NEGATIVE_EXP(value)?BOOST_METAMATH_REMOVE_NEGATIVE_EXP1(value):BOOST_METAMATH_REMOVE_POSITIVE_EXP1(value))

//Convert exponent to int
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT512(value) (BOOST_METAMATH_REMOVE_SIGN(value)>BOOST_METAMATH_EXP512?512:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT256(value) BOOST_METAMATH_POSITIVE_EXP_TO_INT512(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP512(value)>BOOST_METAMATH_EXP256?256:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT128(value) BOOST_METAMATH_POSITIVE_EXP_TO_INT256(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP256(value)>BOOST_METAMATH_EXP128?128:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT64(value)  BOOST_METAMATH_POSITIVE_EXP_TO_INT128(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP128(value)>BOOST_METAMATH_EXP64?64:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT32(value)  BOOST_METAMATH_POSITIVE_EXP_TO_INT64(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP64(value)>BOOST_METAMATH_EXP32?32:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT16(value)  BOOST_METAMATH_POSITIVE_EXP_TO_INT32(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP32(value)>BOOST_METAMATH_EXP16?16:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT8(value)	  BOOST_METAMATH_POSITIVE_EXP_TO_INT16(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP16(value)>BOOST_METAMATH_EXP8?8:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT4(value)	  BOOST_METAMATH_POSITIVE_EXP_TO_INT8(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP8(value)>BOOST_METAMATH_EXP4?4:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT2(value)	  BOOST_METAMATH_POSITIVE_EXP_TO_INT4(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP4(value)>BOOST_METAMATH_EXP2?2:0)
#define BOOST_METAMATH_POSITIVE_EXP_TO_INT1(value)	  BOOST_METAMATH_POSITIVE_EXP_TO_INT2(value)+(BOOST_METAMATH_REMOVE_POSITIVE_EXP2(value)>BOOST_METAMATH_EXP1?1:0)

#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT512(value) (BOOST_METAMATH_REMOVE_SIGN(value)<BOOST_METAMATH_EXP_512 *2.?-512:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT256(value) BOOST_METAMATH_NEGATIVE_EXP_TO_INT512(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP512(value)<BOOST_METAMATH_EXP_256 *2.?-256:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT128(value) BOOST_METAMATH_NEGATIVE_EXP_TO_INT256(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP256(value)<BOOST_METAMATH_EXP_128 *2.?-128:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT64(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT128(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP128(value)<BOOST_METAMATH_EXP_64 *2.?-64:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT32(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT64(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP64(value)<BOOST_METAMATH_EXP_32 *2.?-32:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT16(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT32(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP32(value)<BOOST_METAMATH_EXP_16 *2.?-16:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT8(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT16(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP16(value)<BOOST_METAMATH_EXP_8 *2.?-8:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT4(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT8(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP8(value)<BOOST_METAMATH_EXP_4 *2.?-4:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT2(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT4(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP4(value)<BOOST_METAMATH_EXP_2 *2.?-2:0)
#define BOOST_METAMATH_NEGATIVE_EXP_TO_INT1(value)  BOOST_METAMATH_NEGATIVE_EXP_TO_INT2(value)+(BOOST_METAMATH_REMOVE_NEGATIVE_EXP2(value)<BOOST_METAMATH_EXP_1 *2.?-1:0)

#if BOOST_WORKAROUND(BOOST_MSVC,<=1310)
#define BOOST_METAMATH_EXP_TO_INT(value) (BOOST_METAMATH_REMOVE_SIGN(value)<1.0?BOOST_METAMATH_NEGATIVE_EXP_TO_INT1(value):BOOST_METAMATH_POSITIVE_EXP_TO_INT1(value))
#else
#define BOOST_METAMATH_EXP_TO_INT(value) boost::int16_t(BOOST_METAMATH_REMOVE_SIGN(value)<1.0?BOOST_METAMATH_NEGATIVE_EXP_TO_INT1(value):BOOST_METAMATH_POSITIVE_EXP_TO_INT1(value))
#endif
//Convert int to exponent
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP512(value) ((value)&512?BOOST_METAMATH_EXP512:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP256(value) BOOST_METAMATH_POSITIVE_INT_TO_EXP512(value)*((value)&256?BOOST_METAMATH_EXP256:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP128(value) BOOST_METAMATH_POSITIVE_INT_TO_EXP256(value)*((value)&128?BOOST_METAMATH_EXP128:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP64(value)  BOOST_METAMATH_POSITIVE_INT_TO_EXP128(value)*((value)&64?BOOST_METAMATH_EXP64:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP32(value)  BOOST_METAMATH_POSITIVE_INT_TO_EXP64(value)*((value)&32?BOOST_METAMATH_EXP32:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP16(value)  BOOST_METAMATH_POSITIVE_INT_TO_EXP32(value)*((value)&16?BOOST_METAMATH_EXP16:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP8(value)   BOOST_METAMATH_POSITIVE_INT_TO_EXP16(value)*((value)&8?BOOST_METAMATH_EXP8:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP4(value)   BOOST_METAMATH_POSITIVE_INT_TO_EXP8(value)*((value)&4?BOOST_METAMATH_EXP4:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP2(value)   BOOST_METAMATH_POSITIVE_INT_TO_EXP4(value)*((value)&2?BOOST_METAMATH_EXP2:1.)
#define BOOST_METAMATH_POSITIVE_INT_TO_EXP1(value)   BOOST_METAMATH_POSITIVE_INT_TO_EXP2(value)*((value)&1?BOOST_METAMATH_EXP1:1.)

#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP512(value) ((-(value))&512?BOOST_METAMATH_EXP_512:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP256(value) BOOST_METAMATH_NEGATIVE_INT_TO_EXP512(value)*((-(value))&256?BOOST_METAMATH_EXP_256:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP128(value) BOOST_METAMATH_NEGATIVE_INT_TO_EXP256(value)*((-(value))&128?BOOST_METAMATH_EXP_128:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP64(value)  BOOST_METAMATH_NEGATIVE_INT_TO_EXP128(value)*((-(value))&64?BOOST_METAMATH_EXP_64:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP32(value)  BOOST_METAMATH_NEGATIVE_INT_TO_EXP64(value)*((-(value))&32?BOOST_METAMATH_EXP_32:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP16(value)  BOOST_METAMATH_NEGATIVE_INT_TO_EXP32(value)*((-(value))&16?BOOST_METAMATH_EXP_16:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP8(value)   BOOST_METAMATH_NEGATIVE_INT_TO_EXP16(value)*((-(value))&8?BOOST_METAMATH_EXP_8:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP4(value)   BOOST_METAMATH_NEGATIVE_INT_TO_EXP8(value)*((-(value))&4?BOOST_METAMATH_EXP_4:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP2(value)   BOOST_METAMATH_NEGATIVE_INT_TO_EXP4(value)*((-(value))&2?BOOST_METAMATH_EXP_2:1.)
#define BOOST_METAMATH_NEGATIVE_INT_TO_EXP1(value)   BOOST_METAMATH_NEGATIVE_INT_TO_EXP2(value)*((-(value))&1?BOOST_METAMATH_EXP_1:1.)

#define BOOST_METAMATH_INT_TO_EXP(value) (value<0.0?BOOST_METAMATH_NEGATIVE_INT_TO_EXP1(value):BOOST_METAMATH_POSITIVE_INT_TO_EXP1(value))


//Convert normalised double to int
#define BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTA(value) value*BOOST_METAMATH_EXP30
#define BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTB(value) ((value)*BOOST_METAMATH_EXP30-boost::uint32_t((value)*BOOST_METAMATH_EXP30))*BOOST_METAMATH_EXP31

#if BOOST_WORKAROUND(BOOST_MSVC,<=1310)
#define BOOST_METAMATH_DOUBLE_TO_INTA(value) BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTA(BOOST_METAMATH_NORMALISE(value))
#define BOOST_METAMATH_DOUBLE_TO_INTB(value) BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTB(BOOST_METAMATH_NORMALISE(value))
#else
#define BOOST_METAMATH_DOUBLE_TO_INTA(value) boost::uint32_t(BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTA(BOOST_METAMATH_NORMALISE(value)))
#define BOOST_METAMATH_DOUBLE_TO_INTB(value) boost::uint32_t(BOOST_METAMATH_NORMALISED_DOUBLE_TO_INTB(BOOST_METAMATH_NORMALISE(value)))
#endif

//Convert ints to normalised double
#define BOOST_DOUBLE(value) \
    boost::metamath::double_<\
        boost::metamath::detail::mantissa<\
            BOOST_METAMATH_DOUBLE_TO_INTA(value),\
            BOOST_METAMATH_DOUBLE_TO_INTB(value)\
        >,\
        BOOST_METAMATH_EXP_TO_INT(value),\
        value<0\
    >

#endif //BOOST_METAMATHMATH_DOUBLE_DOUBLE_MACROS_HPP
