# vi: syntax=python:et:ts=4
Import("env")

env.BoostUseLib("system")
env.BoostRunTests(Split("""
    path_test
    operations_test 
    fstream_test
    convenience_test 
    large_file_support_test
    wide_test
    """))
env.BoostCompileTests(Split("""
    deprecated_test
    ../example/mbcopy
    ../example/mbpath
    ../example/simple_ls
    """))
